spring.application.name=cass.check

spring.cassandra.keyspace-name=store
spring.cassandra.contact-points=127.0.0.1:9045
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.request.timeout=10s
#cass4
#spring.cassandra.contact-points=127.0.0.1:9044

##пути до JAVA
casstool.java11.home=/opt/openjdk-11.0.2
casstool.java17.home=/opt/liberica-17.0.7

# Настройки запуска кассандры перед запуском тестирования
## Скрипты иницализации KEYSAPCE
casstool.cass4.create-keyspace-script=src/scripts/scripts_cass4.cql
casstool.cass5.create-keyspace-script=src/scripts/scripts_cass5.cql
casstool.scylla.create-keyspace-script=src/scripts/scripts_scylla.cql

## Скрипт запуска сциллы
casstool.scylla.run-as-daemon-script=src/scripts/scylla_run_as_daemon.sh

##Пути до директории установки кассандры
casstool.cassandra4.path=/opt/apache-cassandra-4.1.10
casstool.cassandra5.path=/opt/apache-cassandra-5.0.5
casstool.scylla.path=/opt/scylladb

##Пути до директории хранения файлов с данными
casstool.cassandra4.data.path=/opt/apache-cassandra-4.1.10/data/data
casstool.cass5.data.path=/opt/apache-cassandra-5.0.5/data/data
casstool.scylla.data.path=/home/dude/scylla-work/data

##Выбор тестируемой версии кассандры
#casstool.cassandra.enable-version=CASS_4
casstool.cassandra.enable-version=CASS_5
#casstool.cassandra.enable-version=SCYLLA

##Выбор JAVA
#casstool.java.version=java11
casstool.java.version=java17

##Выбор GC и XMX
casstool.java.xmx=-Xmx1g
casstool.java.xms=-Xms1g
casstool.java.gc=G1
#casstool.java.gc=CMS
#casstool.java.gc=ZGC


#автосоздание keyspace
casstool.create-keyspace.enable=false
# авто-запуск и авто-остановке кассандны
casstool.start.enable=true
casstool.force-restart.enable=true
casstool.stop.enable=true

#Настройки тестирования: многопоточка и логи
speedtest.multithreads.threads.count=64
speedtest.executing.stat.enabled=true
speedtest.executing.stat.delay=3s


#скорость работы с партиционным ключём
speedtest.benches.set1.enabled=true
speedtest.benches.set1.name=many_small_partitions
speedtest.benches.set1.title=Test many small partitions
speedtest.benches.set1.insert-count=100_000
speedtest.benches.set1.flush-after-insert=true
speedtest.benches.set1.select-time-sec=5
##speedtest.benches.set1.retry=1
##speedtest.benches.set1.retry-select=2

##скорость работы с кластерным ключём
speedtest.benches.set2.enabled=false
speedtest.benches.set2.name=one_big_partition
speedtest.benches.set2.title=Test big partition with search by cluster key
speedtest.benches.set2.insert-count=100_000
speedtest.benches.set2.retry=3
#
##поиск через промежуточную табличку поиска
speedtest.benches.set3.enabled=false
speedtest.benches.set3.name=find_by_searchtable
speedtest.benches.set3.title=Test search by custom searchtable
speedtest.benches.set3.insert-count=100_000
#speedtest.benches.set3.retry=3
#
#поиск через обычный индекс
speedtest.benches.set4.enabled=false
speedtest.benches.set4.name=find_by_secondary_index
speedtest.benches.set4.title=Test search by Regular Secondary Index (2i)
speedtest.benches.set4.insert-count=1_000_000
#speedtest.benches.set4.retry=1
#speedtest.benches.set4.select-time-sec=5
#
##поиск через SAI
speedtest.benches.set5.enabled=false
speedtest.benches.set5.name=find_by_sai
speedtest.benches.set5.title=Test search by SAI
speedtest.benches.set5.insert-count=1_000_000
#speedtest.benches.set5.retry=1
#
##Векторый по SAI vector(128)
speedtest.benches.set6.enabled=false
speedtest.benches.set6.name=find_by_sai_vector
speedtest.benches.set6.title=Test search by SAI Vector(128)
#speedtest.benches.set6.insert-count=100_000,200_000,500_000,1_000_000,2_000_000
speedtest.benches.set6.insert-count=10_000
#speedtest.benches.set6.retry=1

#TODO: LWT bench !
#TODO:  SAI vector крешнулся на 2кк. надо перепроверять
#TODO: SCYLLA отвалилась
#TODO: pid фаил вернуть в дирректорию запуска
#DONE: уметь запускать скрипт инициализации БД
#DONE (не доделал): инфо о настройках кассандры: версия JAVA, версия GC, Версия касс, формат таблиц (trie+bti или skiplist + big)

